UBUNTU: SAUCE: ubuntu_performance_pts: Use format string when printing float
Avoids the following crash:

21:24:57 INFO | 		FAIL	ubuntu_performance_pts.ubuntu_performance_pts_john-the-ripper-blowfish	ubuntu_performance_pts.ubuntu_performance_pts_john-the-ripper-blowfish	timestamp=1598649897	localtime=Aug 28 21:24:57	Unhandled TypeError: cannot concatenate 'str' and 'float' objects
  Traceback (most recent call last):
    File "/raid/upt.7623-1hNSLqcbBp/autotest/client/shared/test.py", line 823, in _call_test_function
      return func(*args, **dargs)
    File "/raid/upt.7623-1hNSLqcbBp/autotest/client/shared/test.py", line 291, in execute
      postprocess_profiled_run, args, dargs)
    File "/raid/upt.7623-1hNSLqcbBp/autotest/client/shared/test.py", line 212, in _call_run_once
      self.run_once(*args, **dargs)
    File "/raid/upt.7623-1hNSLqcbBp/autotest/client/tests/ubuntu_performance_pts/ubuntu_performance_pts.py", line 297, in run_once
      run_funcs[subtest](test_name, subtest)
    File "/raid/upt.7623-1hNSLqcbBp/autotest/client/tests/ubuntu_performance_pts/ubuntu_performance_pts.py", line 232, in run_john_the_ripper_blowfish
      self.print_stats('john_the_ripper_blowfish', cmd)
    File "/raid/upt.7623-1hNSLqcbBp/autotest/client/tests/ubuntu_performance_pts/ubuntu_performance_pts.py", line 214, in print_stats
      print(benchmark + "_" + field.lower() + "_minimum " + minimum)
  TypeError: cannot concatenate 'str' and 'float' objects

Fixes: 77c2badedd4b ("UBUNTU: SAUCE: python3 print() parentheses compatibility fix")
Signed-off-by: dann frazier <dann.frazier@canonical.com>
Acked-by: sean.feole <sean.feole@canonical.com>