UBUNTU: SAUCE: fix git clone failures and setups not being idempotent
The tests and their setup should be idempotent.  They should not fail
(neither pass) because it is second run on a target.  The setup() should
prepare everything needed for the test assuming that some steps could be
already executed from previous runs.

Recent change in autotest caused setup() to be executed every time which
lead to 'git clone' failures in few tests executing setup multiple
times, for example ubuntu_performance_thermal:

    11:03:11 DEBUG| Running 'git clone git://kernel.ubuntu.com/cking/stress-ng'
    11:03:11 ERROR| [stderr] fatal: destination path 'stress-ng' already exists and is not an empty directory.
    11:03:11 ERROR| Exception escaping from test:
    Traceback (most recent call last):
      File "/home/ubuntu/autotest/client/shared/test.py", line 387, in _exec
        *p_args, **p_dargs)
      File "/home/ubuntu/autotest/client/shared/utils.py", line 868, in update_version
        install(*args, **dargs)
      File "/home/ubuntu/autotest/client/tests/ubuntu_performance_thermal/ubuntu_performance_thermal.py", line 96, in setup
        self.results = utils.system_output('git clone git://kernel.ubuntu.com/cking/stress-ng', retain_output=True)
      File "/home/ubuntu/autotest/client/shared/utils.py", line 1271, in system_output
        verbose=verbose, args=args).stdout
      File "/home/ubuntu/autotest/client/shared/utils.py", line 922, in run
        "Command returned non-zero exit status")
    CmdError: Command <git clone git://kernel.ubuntu.com/cking/stress-ng> failed, rc=128, Command returned non-zero exit status
    * Command:
        git clone git://kernel.ubuntu.com/cking/stress-ng

Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>
Acked-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>