xfstests, ubuntu_zfs_xfs_generic: depend on libblkid-dev
Recently in cosmic tests have started failing with this message:

 FATAL ERROR: could not find a valid BLKID header.
 Install the Block device ID development package.

Do as instructed, and make these tests install libblkid-dev.

Signed-off-by: Seth Forshee <seth.forshee@canonical.com>