UBUNTU: SAUCE: ubuntu_kernel_selftests: use different clang / llvm to build bpf for the net test
BugLink: https://bugs.launchpad.net/bugs/1882559

The net test in ubuntu_kernel_selftests will fail to build on B-5.4 with:
   progs/test_core_reloc_ints.c:32:6: error: use of unknown builtin
   '__builtin_preserve_access_index' [-Wimplicit-function-declaration]

We have a series of fixes for ubuntu_bpf test build issues with
different clang / llvm versions:
  077abb85af8b ("UBUNTU: SAUCE: ubuntu_bpf: build with clang-9 on B-5.3")
  a4eac63ea532 ("UBUNTU: SAUCE: ubuntu_bpf: build with clang-9 on B-5.4")
  79fdddfe6650 ("UBUNTU: SAUCE: ubuntu_bpf: use clang-10 and llvm-10 for F-5.6")

Reflect these changes into ubuntu_kernel_selftests for the net test.

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>