UBUNTU: SAUCE: ubuntu_kernel_selftests: bump clang to clang-13 for Linux 5.13
Linux 5.13 selftests/bpf require clang-13 (see also
selftests/bpf/README.rst::Kernel function call test and Clang version)
to fix a FTBFS:
...
libbpf: elf: skipping unrecognized data section(5) .rodata.str1.1
libbpf: elf: skipping unrecognized data section(5) .rodata.str1.1
libbpf: failed to find BTF for extern 'tcp_cong_avoid_ai' [27] section: -2
Error: failed to open BPF object file: No such file or directory
...

Signed-off-by: Paolo Pisati <paolo.pisati@canonical.com>
Acked-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
Acked-by: Thadeu Lima de Souza Cascardo <cascardo@canonical.com>
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>