ubuntu_kernel_selftests: net tests require libnuma-dev
The net selftests are failing with a build failure on some
architectures:

  reuseport_bpf_numa.c:23:18: fatal error: numa.h: No such file or directory
   #include <numa.h>
                    ^
  compilation terminated.
  make: *** [reuseport_bpf_numa] Error 1

Installing libnuma-dev fixes this error.

Signed-off-by: Seth Forshee <seth.forshee@canonical.com>