UBUNTU: SAUCE: ubuntu_performance_stream: Use format string when printing int
Prevents the following crash:

21:21:24 INFO | 		FAIL	ubuntu_performance_stream.ubuntu-performance-stream	ubuntu_performance_stream.ubuntu-performance-stream	timestamp=1598649684	localtime=Aug 28 21:21:24	Unhandled TypeError: cannot concatenate 'str' and 'int' objects
  Traceback (most recent call last):
    File "/raid/upt.7463-KmhNcOYQaU/autotest/client/shared/test.py", line 823, in _call_test_function
      return func(*args, **dargs)
    File "/raid/upt.7463-KmhNcOYQaU/autotest/client/shared/test.py", line 291, in execute
      postprocess_profiled_run, args, dargs)
    File "/raid/upt.7463-KmhNcOYQaU/autotest/client/shared/test.py", line 212, in _call_run_once
      self.run_once(*args, **dargs)
    File "/raid/upt.7463-KmhNcOYQaU/autotest/client/tests/ubuntu_performance_stream/ubuntu_performance_stream.py", line 246, in run_once
      enough_ram = self.get_sysinfo()
    File "/raid/upt.7463-KmhNcOYQaU/autotest/client/tests/ubuntu_performance_stream/ubuntu_performance_stream.py", line 229, in get_sysinfo
      print('page_size ' + page_size)
  TypeError: cannot concatenate 'str' and 'int' objects

Fixes: 77c2badedd4b ("UBUNTU: SAUCE: python3 print() parentheses compatibility fix")
Signed-off-by: dann frazier <dann.frazier@canonical.com>
Acked-by: sean.feole <sean.feole@canonical.com>