UBUNTU: SAUCE: ubuntu_kernel_selftests: abort early for TEST-build failure
Abort sub-tests execution if the TEST-build task has failed to build
the sub-tests inside the TEST directory.

So that we won't get test failures because of this build issue.

Output example:
    END ERROR    ubuntu_kernel_selftests.net-build
    Persistent state client._record_indent now set to 1
    Persistent state client.unexpected_reboot deleted
    ERROR: test suite 'net' failed to build, skipping all the sub tests
    Test has timeout: 600 sec.
    START    ubuntu_kernel_selftests.ptrace-build

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>