UBUNTU SAUCE: ubuntu_btrfs_kernel_fixes: remove redundant mkfs /mount in 03cb4fb
There is set of duplicated mkfs / mount command in the script,
it will cause the system to complain:
    ERROR: /dev/loop0 is mounted

Remove it to fix this issue.

Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>